### ISSUE TITLE
Malicious Software?

### ISSUE THREAD

**Issue by FlixMa** [SlidePilot/SlidePilot#1]
### Bug description

Downloading the app and running it produces the following message:

> “SlidePilot.app” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information. Safari downloaded this file today at 23:20 from slidepilotapp.com.

The system preferences "Security & Privacy" page says it cannot be opened because it is not from an identified developer.

### Steps to reproduce

download, unzip and open

### Expected behavior

The app opens normally

### Actual behavior

shows warning

### Details
* macOS Version: 10.15.4 (19E287)
* SlidePilot Version: 1.2.0

**Comment by SlidePilot** [comment]
Thanks for your report. To open the app you have to hold the ctrl-key while right-clicking on the app and then select "Open", all while still holding the ctrl-key. A popup will appear where you can select to open the app. This has to be done only on the first start of the application.

So why do you have to do this? From the website:

> The popup appears because the app is not signed. Signing requires being enrolled in the Apple Developer Program, which costs 99 USD per year. If we can cover these costs by donations, we would be more than happy to officially sign the app.

**Comment by FlixMa** [comment]
Sorry for the inconvenience. I looked at your docs but somehow didn't came across the FAQs.
Thanks!

**Comment by SlidePilot** [comment]
No problem at all, better safe than sorry! Thanks for the feedback, I will add installation instructions to the documentation.

**Comment by FlixMa** [comment]
Just realised that the FAQs in the docs are different from those on the main page:
https://slidepilot.gitbook.io/slidepilot/faq
https://slidepilotapp.com/#faq

**Comment by SlidePilot** [comment]
True that, thanks for the notice. I will fix that as well! :)
